version: '3'
services:
  space:
    build: .
    ports:
     - "8766:8766/udp"
     - "27016:27016/udp"
    volumes:
     - ./space:/mnt/root/space-engineers-server
    environment:
     - SERVER_NAME=DefaultSavePath
